[project]
name = "elegoo-robot-car4"
version = "1.0.1"
description = "Python software for controlling the Elegoo Smart Robot Car V4.0"
readme = "README.md"
authors = [
    { name = "Michele De Stefano" }
]
requires-python = ">=3.12"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Education",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

dependencies = [
    "numpy>=2.0",
    "opencv-python>=4.13.0.90",
    "pygame-ce>=2.5.6",
    "requests>=2.32.5",
]

[project.optional-dependencies]
vision = [
    "lap>=0.5.12",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
    "ultralytics>=8.4.8",
]
navigation = ["scipy>=1.17.0"]
calibration = [
    "matplotlib>=3.10.8",
    "pandas>=3.0.0",
    "seaborn>=0.13.2",
]

[project.urls]
Homepage = "https://github.com/micdestefano/elegoo-robot-car4"
Documentation = "https://github.com/micdestefano/elegoo-robot-car4/blob/main/README.md"
Download = "https://pypi.org/project/elegoo-robot-car4/#files"
Source = "https://github.com/micdestefano/elegoo-robot-car4"
Issues = "https://github.com/micdestefano/elegoo-robot-car4/issues"


[project.scripts]
elegoo-smartcar-control = "elegoo_robot_car4.elegoo_smartcar_control:main"
elegoo-smartcar-legacy = "elegoo_robot_car4.elegoo_smartcar_control:legacy_main"

[build-system]
requires = ["uv_build>=0.10.4,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipython>=9.9.0",
]
test = [
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.1",
]

[tool.ruff]
line-length = 80

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

[tool.rumdl]
disable = ["MD013"]

[tool.coverage.run]
omit = [
    # This file contains the game engine and an automatic test
    # is useless. It must be tested manually.
    "elegoo_smartcar_control.py",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true
